linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goimports
    - misspell

linters-settings:
  goimports:
    local-prefixes: github.com/nishchay/lore

issues:
  exclude-rules:
    - path: _test\.go
      linters: [errcheck]
