package config

import (
	"os"
	"path/filepath"

	"github.com/BurntSushi/toml"
)

type Config struct {
	LLM struct {
		Provider string `toml:"provider"`
		Model    string `toml:"model"`
		Endpoint string `toml:"endpoint"`
	} `toml:"llm"`
	Extraction struct {
		MinTasks          int `toml:"min_tasks"`
		TaskRetentionDays int `toml:"task_retention_days"`
	} `toml:"extraction"`
	NodeResolution struct {
		MinConfidence       float64 `toml:"min_confidence"`
		TagOverlapThreshold float64 `toml:"tag_overlap_threshold"`
	} `toml:"node_resolution"`
	Output struct {
		Color bool `toml:"color"`
	} `toml:"output"`
}

func Defaults() Config {
	var c Config
	c.LLM.Provider = "ollama"
	c.LLM.Model = "llama3"
	c.LLM.Endpoint = "http://localhost:11434"
	c.Extraction.MinTasks = 1
	c.Extraction.TaskRetentionDays = 30
	c.NodeResolution.MinConfidence = 0.4
	c.NodeResolution.TagOverlapThreshold = 0.5
	c.Output.Color = true
	return c
}

const defaultTOML = `# Lore repository configuration
# Generated by lore init — edit to customize

[llm]
provider = "ollama"
model    = "llama3"
endpoint = "http://localhost:11434"

[extraction]
min_tasks           = 1
task_retention_days = 30

[node_resolution]
min_confidence        = 0.4
tag_overlap_threshold = 0.5

[output]
color = true
`

// WriteDefault writes the default config.toml to loreRoot.
func WriteDefault(loreRoot string) error {
	return os.WriteFile(filepath.Join(loreRoot, "config.toml"), []byte(defaultTOML), 0644)
}

// Load merges global config (~/.config/lore/config.toml) then per-repo config.
func Load(loreRoot string) (Config, error) {
	cfg := Defaults()

	globalPath := filepath.Join(os.Getenv("HOME"), ".config", "lore", "config.toml")
	if _, err := os.Stat(globalPath); err == nil {
		if _, err := toml.DecodeFile(globalPath, &cfg); err != nil {
			return cfg, err
		}
	}

	localPath := filepath.Join(loreRoot, "config.toml")
	if _, err := os.Stat(localPath); err == nil {
		if _, err := toml.DecodeFile(localPath, &cfg); err != nil {
			return cfg, err
		}
	}

	return cfg, nil
}
